-- Câu 4
USE master
IF db_id('QLTH') IS NOT NULL
	DROP DATABASE QLTH
GO
CREATE TABLE SinhVien (
	MaSV VARCHAR(8) NOT NULL
	,HoTen NVARCHAR(50) NOT NULL
	,NgaySinh DATETIME NOT NULL
	,DiemTB FLOAT NOT NULL DEFAULT 0
	,CONSTRAINT PK_SinhVien PRIMARY KEY (MASV)
	)

CREATE TABLE CanBo (
	MaCB VARCHAR(8) NOT NULL
	,HoTen NVARCHAR(50) NOT NULL
	,NgaySinh DATETIME NOT NULL
	,DienThoai VARCHAR(10)
	,MaBM INT NOT NULL
	,CONSTRAINT PK_CanBo PRIMARY KEY (MaCB)
	)

CREATE TABLE DangKy (
	MaSV VARCHAR(8) NOT NULL
	,MaMH VARCHAR(8) NOT NULL
	,NgayDangKy DATETIME NOT NULL DEFAULT getdate()
	,CONSTRAINT PK_DangKy PRIMARY KEY (
		MaSV
		,MaMH
		)
	)

CREATE TABLE MonHoc (
	MaMH VARCHAR(8) NOT NULL
	,TenMH NVARCHAR NOT NULL
	,MaCBPhuTrach VARCHAR(8)
	,CONSTRAINT PK_MonHoc PRIMARY KEY (MaMH)
	)

CREATE TABLE BoMon (
	MaBM INT NOT NULL identity(1, 1)
	,MaCBQuanLy VARCHAR(8)
	,CONSTRAINT PK_BoMon PRIMARY KEY (MaBM)
	)

ALTER TABLE CanBo ADD CONSTRAINT FK_CanBo_BoMon FOREIGN KEY (MaBM) REFERENCES BoMon (MaBM);

ALTER TABLE MonHoc ADD CONSTRAINT FK_MonHoc_CanBo FOREIGN KEY (MaCBPhuTrach) REFERENCES CanBo (MaCB);

ALTER TABLE BoMon ADD CONSTRAINT FK_BoMon_CanBo FOREIGN KEY (MaCBQuanLy) REFERENCES CanBo (MaCB);

-- Câu 5
CREATE SCHEMA GiaoVien AUTHORIZATION GiaoVien

CREATE SCHEMA SinhVien AUTHORIZATION SinhVien

CREATE SCHEMA HeThong AUTHORIZATION dbo

 -- Câu 6
ALTER SCHEMA GiaoVien transfer dbo.BoMon

ALTER SCHEMA GiaoVien transfer dbo.CanBo

ALTER SCHEMA GiaoVien transfer dbo.CanBo

-- Câu 7
